name: macOS

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: make setup
      run: make setup

    - name: make bin/roba
      run: make bin/roba
    - name: 'export binary'
      uses: actions/upload-artifact@v2
      with:
          name: roba
          path: bin/roba
    - name: make clean
      run: make clean

    - name: make bin/roba CXX=g++
      run: make bin/roba CXX=g++
    - name: make clean
      run: make clean
